### ISSUE TITLE
cant' made it work in OF 0.11...

### ISSUE THREAD

**Issue by moebiussurfing** [elliotwoods/ofxSplashScreen#1]
I made it compile by adding this to ofxSplashScreen:
`#include "GLFW/glfw3.h" `

this avoids errors but the splash screen is not drawn. image is loaded but nothing happens.
just a pause of default 3000 ms time without drawing the window.

I am in Windows 10 and VS2017.

**Comment by elliotwoods** [comment]
Hey!
This add on hasn’t worked for a while.
The new ofWindow system might work as a replacement API (I’m using raw glfw here)
A lot has changed so it would probably need a rewrite of all the important code .
